{
  "extends": [
    "plugin:vue/vue3-essential",
    "eslint:recommended"
  ],
  "parserOptions": {
    "parser": "@babel/eslint-parser",
    "requireConfigFile": false
  }
  ,
  
  "globals": {
    "definePageMeta": "readonly",
    "defineAppConfig":"readonly"
  
},
rules:{
  'vue/multi-word-component-names': 0
}
}